openapi: 3.0.0
info:
  title: Products API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get a list of products
      description: Returns a list of products with details such as SKU, name, and price.
      responses:
        '200':
          description: Successful response with the list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        sku:
          type: string
          description: The Stock Keeping Unit (SKU) of the product.
        name:
          type: string
          description: The name of the product.
        price:
          type: number
          format: float
          description: The price of the product.
      required:
        - sku
        - name
        - price